#!/usr/bin/env python
import sys
import numpy as np
import sklearn.metrics
from wplotlib import lines

np.set_printoptions(precision=4)
np.set_printoptions(threshold=30)
np.set_printoptions(linewidth=300)
np.set_printoptions(suppress=True)
np.set_printoptions(threshold=sys.maxsize)

c = ['#FFDD44', '#00FF44', '#0000FF', '#00AAAA']

m = np.zeros(30)
x = np.atleast_2d(np.arange(0,3,0.1)).T
K = sklearn.metrics.pairwise.rbf_kernel(x)


lp = lines()
for i in range(4):
	y = np.random.multivariate_normal(m, K, size=None, check_valid='warn', tol=1e-8)
	lp.add_plot(x, y, color=c[i])

lp.set_title('Randomly generated by a Gaussian Process')
lp.show()



